export { default as MainView } from './MainView'
export { NotFoundView } from './NotFoundView'
export { default as AboutView } from './AboutView'
export { default as NewsView } from './NewsView'
export { default as ContactView } from './ContactView'
export { default as BlogView } from './BlogView'
